In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

numpy adalah library python yang digunakan untuk mengelola komputasi matriks


In [ ]:
dataset = pd.read_csv('DataBalitaGiziBurukBandung.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Sukasari' 1500000 12.0]
 ['Sukasari' 1500000 8.0]
 ['Sukasari' 1500000 6.0]
 ['Sukasari' 1500000 2.0]
 ['Sukajadi' 1500000 16.0]
 ['Sukajadi' 1500000 nan]
 ['Sukajadi' 2000000 11.0]
 ['Cicendo ' 1000000 6.0]
 ['Cicendo ' 1000000 6.0]
 ['Andir' 2000000 nan]
 ['Andir' 2000000 6.0]
 ['Cidadap' 2000000 12.0]
 ['Cidadap' 2000000 12.0]
 ['Coblong' 2000000 nan]
 ['Coblong' 2000000 10.0]
 ['Coblong' 2000000 2.0]
 ['Coblong' 2000000 7.0]
 ['Bandung Wetan' 2500000 2.0]
 ['Bandung Wetan' 2500000 13.0]]


In [ ]:
print(y)

['yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'no'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Sukasari' 1500000 12.0]
 ['Sukasari' 1500000 8.0]
 ['Sukasari' 1500000 6.0]
 ['Sukasari' 1500000 2.0]
 ['Sukajadi' 1500000 16.0]
 ['Sukajadi' 1500000 nan]
 ['Sukajadi' 2000000 11.0]
 ['Cicendo ' 1000000 6.0]
 ['Cicendo ' 1000000 6.0]
 ['Andir' 2000000 nan]
 ['Andir' 2000000 6.0]
 ['Cidadap' 2000000 12.0]
 ['Cidadap' 2000000 12.0]
 ['Coblong' 2000000 nan]
 ['Coblong' 2000000 10.0]
 ['Coblong' 2000000 2.0]
 ['Coblong' 2000000 7.0]
 ['Bandung Wetan' 2500000 2.0]
 ['Bandung Wetan' 2500000 13.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('ecoder',OneHotEncoder(),[0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))


In [ ]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 12.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 8.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 6.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 2.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 1500000.0 16.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 1500000.0 8.1875]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 2000000.0 11.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1000000.0 6.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1000000.0 6.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 2000000.0 8.1875]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 2000000.0 6.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 2000000.0 12.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 2000000.0 12.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 8.1875]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 10.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 2.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 7.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 2500000.0 2.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 2500000.0 13.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 2000000.0 12.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 2000000.0 12.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 1500000.0 8.1875]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 2.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 2.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 2000000.0 11.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 2000000.0 6.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 6.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 10.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 1500000.0 16.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 7.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1000000.0 6.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 8.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 2000000.0 8.1875]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 1500000.0 12.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 2500000.0 13.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 2500000.0 2.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 2000000.0 8.1875]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1000000.0 6.0]]


In [ ]:
print(y_train)

[0 1 1]


In [ ]:
print(y_test)

[1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 0.0 0.7071067811865476 0.0 -0.7071067811865475 0.0
  0.7071067811865479 0.7071067811865479]
 [0.0 0.0 0.0 0.7071067811865476 0.0 -0.7071067811865475 0.0
  0.7071067811865479 0.7071067811865479]
 [0.0 0.0 0.0 -1.414213562373095 0.0 1.4142135623730951 0.0
  -1.4142135623730947 -1.4142135623730947]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 -1.414213562373095 0.0 -0.7071067811865475 1.0
  -1.4142135623730947 -4.857012152740384]
 [0.0 0.0 0.0 -1.414213562373095 1.0 -0.7071067811865475 0.0
  0.7071067811865479 -4.857012152740384]
 [0.0 0.0 0.0 -1.414213562373095 0.0 1.4142135623730951 0.0
  0.7071067811865479 0.15069488779385473]
 [1.0 0.0 0.0 -1.414213562373095 0.0 -0.7071067811865475 0.0
  0.7071067811865479 -2.631364579169611]
 [0.0 0.0 0.0 -1.414213562373095 0.0 -0.7071067811865475 1.0
  -1.4142135623730947 -2.631364579169611]
 [0.0 0.0 0.0 -1.414213562373095 1.0 -0.7071067811865475 0.0
  0.7071067811865479 -0.40571700559883844]
 [0.0 0.0 0.0 -1.414213562373095 0.0 1.4142135623730951 0.0
  -1.4142135623730947 2.9327543547573205]
 [0.0 0.0 0.0 -1.414213562373095 1.0 -0.7071067811865475 0.0
  0.7071067811865479 -2.074952685776918]
 [0.0 0.0 1.0 -1.414213562373095 0.0 -0.7071067811865475 0.0
  -3.5355339059327373 -2.631364579169611]
 [0.0 0.0 0.0 -1.414213562373095 0.0 -0.7071067811865475 1.0
  -1.41421356237

In [ ]:
from google.colab import drive
drive.mount('/content/drive')